package com.launchcode.cheese.models;





import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
@Table(name="cheeses")
public class Cheese {


    @Id //signifies field is primary key
    @GeneratedValue //auto generated by the database
    //@Column(name="ID")
    private int cheeseID;

    @NotNull
    @Size(min=3, max=15, message="Cheese name must be between 3 and 15 characters")
    private String name;

    @NotNull
    @Size(min=1, message = "Description must not be empty")
//    @Transient means you don't want it to persist
    private String description;


    @ManyToOne
    private Category category;

    private CheeseRating rating;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getCheeseID() {
        return cheeseID;
    }

    public void setCheeseID(int cheeseID) {
        this.cheeseID = cheeseID;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public CheeseRating getRating() {
        return rating;
    }

    public void setRating(CheeseRating rating) {
        this.rating = rating;
    }
}
